### ISSUE TITLE
Insert id ?

### ISSUE THREAD

**Issue by ZARk-be** [upnxt/upnxt-dapper-cqrs#1]
Hi

found your article, i didn't know CQRS before, and like your implementation with dapper.

Is there a reason why ICommand.Execute doesn't return an int to have the inserted identity ?

**Comment by upnxt** [comment]
Glad you found it useful! I like ICommand to be void as not every use case requires a return value. If you need an identifier back you can use session.Execute/Query to return the value and update the model passed into the constructor by reference.

private readonly Animal _animal;

public SaveAnimal(Animal animal)
{
   _animal = animal;
}

public void Execute(ISession session)
{
   var id = session.Query<int>("INSERT INTO ...; SELECT CAST(SCOPE_IDENTITY() as int);")
   _animal.Id = id;
}
